using System;
using System.Collections.Generic;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
;

namespace Content.Client.Skills
{
    [GenerateTypedNameReferences]
    public sealed partial class SkillsMenu : DefaultWindow
    {
        public SkillsMenu()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
        }
    }
}
